[package]
name = "fs"
version = "0.1.0"
edition = "2021"

[dependencies]
spin = "0.9.8"
lazy_static = "1.5.0"
bitflags = "2.6.0"
chrono = { version = "0.4.38", default-features = false, features = ["alloc"] }

[features]